from __future__ import annotations
from typing import Protocol, List, Optional
from drone_core.domain.models import Vehicle, VehicleStatus, Mission, MissionStatus, Waypoint

class VehicleRepo(Protocol):
    async def add(self, v: Vehicle) -> Vehicle: ...
    async def get(self, vehicle_id: str) -> Optional[Vehicle]: ...
    async def list_all(self) -> List[Vehicle]: ...
    async def list_free(self) -> List[Vehicle]: ...
    async def set_status(self, vehicle_id: str, status: VehicleStatus) -> None: ...
    async def update(self, v: Vehicle) -> None: ...

class MissionRepo(Protocol):
    async def create(self, m: Mission) -> Mission: ...
    async def get(self, mission_id: str) -> Optional[Mission]: ...
    async def set_status(self, mission_id: str, status: MissionStatus) -> None: ...
    async def assign_vehicle(self, mission_id: str, vehicle_id: str) -> None: ...
    async def save_waypoints(self, mission_id: str, wps: List[Waypoint]) -> None: ...
    async def list_active(self) -> List[Mission]: ...
